"""
Post-processing utilities for PDB-derived SVG diagrams.

Provides functions to grey out unresolved (missing) nucleotide positions
in SVG diagrams generated by R2DT/Traveler/R2R.

Copyright [2009-present] EMBL-European Bioinformatics Institute
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import List, Optional

# Nucleotide characters that can appear in the SVG text elements
_NUCLEOTIDE_RE = re.compile(r"^[ACGUTNacgutn]$")

# SVG namespace (Traveler output uses it)
_SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", _SVG_NS)


def _get_nucleotide_position(title_text: str) -> Optional[int]:
    """
    Extract the 0-based nucleotide position from a ``<title>`` element.

    Traveler/R2R titles look like::

        4 (position.label in template: 4.G)

    The leading integer is the 0-based index in the input sequence.

    Args:
        title_text: Text content of a ``<title>`` element.

    Returns:
        0-based position integer, or ``None`` if not parseable.
    """
    if not title_text:
        return None
    if match := re.match(r"^(\d+)\b", title_text.strip()):
        return int(match.group(1))
    return None


# pylint: disable=too-many-branches
def grey_out_unresolved(svg_path: str, resolved_mask: List[bool]) -> bool:
    """
    Grey out unresolved nucleotides in an SVG diagram.

    Each nucleotide in the Traveler/R2R SVG is a ``<g>`` element containing
    a ``<title>`` (with the 0-based position) and a ``<text>`` (with the
    single nucleotide letter).  For positions where ``resolved_mask`` is
    ``False``, the ``<text>`` CSS class is changed from ``"black"`` to
    ``"gray"``.

    Also greys out backbone ``<line>`` elements that connect two unresolved
    positions (identified by adjacent grey nucleotides).

    Args:
        svg_path: Path to the SVG file (modified **in place**).
        resolved_mask: Boolean list aligned to the full sequence
            (``True`` = resolved, ``False`` = unresolved).

    Returns:
        ``True`` if any nucleotides were greyed out, ``False`` otherwise.
    """
    path = Path(svg_path)
    if not path.exists():
        return False

    tree = ET.parse(str(path))
    root = tree.getroot()

    # Collect positions that should be greyed out.
    # In the Traveler/R2R SVG, nucleotide positions are 1-based
    # (position 0 = 5' label, position N+1 = 3' label).
    # The resolved_mask is 0-based, so SVG position = mask_index + 1.
    unresolved_svg_positions = {
        i + 1 for i, resolved in enumerate(resolved_mask) if not resolved
    }

    if not unresolved_svg_positions:
        return False

    changed = False

    # Walk all <g> elements looking for nucleotide groups
    for g_elem in root.iter():
        tag = g_elem.tag.split("}")[-1] if "}" in g_elem.tag else g_elem.tag
        if tag != "g":
            continue

        # Look for <title> child to identify position
        title_elem = None
        text_elem = None
        for child in g_elem:
            child_tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag
            if child_tag == "title":
                title_elem = child
            elif child_tag == "text":
                text_elem = child

        if title_elem is None or text_elem is None:
            continue

        pos = _get_nucleotide_position(title_elem.text)
        if pos is None:
            continue

        # Check if this is a nucleotide (single letter)
        text_content = (text_elem.text or "").strip()
        if not _NUCLEOTIDE_RE.match(text_content):
            continue

        if pos in unresolved_svg_positions:
            # Change class to "gray"
            current_class = text_elem.get("class", "")
            new_class = current_class.replace("black", "gray")
            if new_class == current_class:
                # No "black" class — just set to gray
                new_class = "gray"
            text_elem.set("class", new_class)
            changed = True

    # Write back
    if changed:
        tree.write(str(path), xml_declaration=True, encoding="unicode")

    return changed


def grey_out_svg_files(
    output_folder: str,
    structure_id: str,
    resolved_mask: List[bool],
    quiet: bool = False,
) -> int:
    """
    Apply grey-out post-processing to all SVG variants in the output tree.

    Looks for the main SVG, colored SVG, and thumbnail SVG files produced
    by the ``templatefree`` pipeline and greys out unresolved nucleotides
    in each.

    Args:
        output_folder: Path to the ``results`` folder produced by
            ``templatefree``.
        structure_id: The structure identifier (used in filename patterns).
        resolved_mask: Boolean list for the full sequence.
        quiet: Suppress output if ``True``.

    Returns:
        Number of SVG files modified.
    """
    results_path = Path(output_folder)
    count = 0

    # Candidate SVG paths (relative to results folder)
    candidates = [
        results_path / "results" / "svg" / f"{structure_id}.svg",
        results_path / "results" / "svg" / f"{structure_id}.colored.svg",
        results_path / "results" / "thumbnail" / f"{structure_id}.thumbnail.svg",
    ]

    for svg_path in candidates:
        if svg_path.exists():
            modified = grey_out_unresolved(str(svg_path), resolved_mask)
            if modified:
                count += 1
                if not quiet:
                    print(f"  Greyed out unresolved nucleotides in {svg_path.name}")

    return count
